ami_owner: "099720109477"
ami_name: "ubuntu/images/hvm-ssd/ubuntu-cosmic-18.10-amd64-server"
ami_version: "20190307"
regions: [ "eu-central-1", "eu-west-1" ]

attendee_prefix: attendee_
infra_name: "clt_lab"
vpc_cidr: "10.1.0.0/16"
subnet_cidr: "10.1.0.0/22"
