---

- name: prerequesites
  hosts: localhost
  gather_facts: false

  vars:

  tasks:

  - name: include configuration
    include_vars:
      file: configuration.yml

  - name: include attendees
    include_vars:
      file: attendees.yml

  - name: send email
    mail:
      from: "Andreas Scherbaum <ads@wars-nicht.de>"
      to: "{{ _attendee['name'] }}"
      charset: utf8
      subject: "CLT 2021 Ansible Workshop - Vorbereitungen"
      body: "{{lookup('file', 'templates/prereq_mail.txt')}}"
    loop: "{{ attendees }}"
    loop_control:
      loop_var: _attendee
      label: "{{ _attendee.id }} - {{ _attendee.name }}"
